module.exports = {
  'WEBSITE_HOSTNAME': "https://8fd4418d.ngrok.io",
  'MICROSOFT_APP_ID': "***REMOVED***",
  'MICROSOFT_APP_PASSWORD': "***REMOVED***",
  'FACEBOOK_APP_ID': "***REMOVED***",
  'FACEBOOK_APP_SECRET': "***REMOVED***",
  'FACEBOOK_PAGE_TOKEN': "EAAN47LGyyhsBAEGfwh2nZBK2JYYVs432ZCVujDY9U1n7RQOClCLlrmJgQmqsj6CJkCg4Fz7L2ANSWguzO3fTZBW0pfMbwX4pZBZC3Sf1RE04luxKp8eEL5Hv6ywKs2DSUbVnKjbZCvBjTIrCC7XCtv12eeu8xZAAAZB6pfZAuD3kkPgZDZD",
  '***REMOVED***': "***REMOVED***",
  'TOKEN_SECRET': "Alenvi"
}
